export { articleDetailsPageReducer } from './model/slice'
export { ArticleDetailsPageAsync as ArticleDetailsPage } from './ui/ArticleDetailsPage/ArticleDetailsPage.async'
export type { ArticleDetailsCommentsSchema } from './model/types/ArticleDetailsCommentsSchema'
export type { articleDetailsPageRecomendationsSchema } from './model/types/articleDetailsPageRecomendationsSchema'
export type { ArticleDetailsPageSchema } from './model/types'
